server:
  tomcat:
    # 이 값을 -1로 설정하면 크기 제한 없이 모두 처리 후 응답을 보냅니다.
    # spring.servlet.multipart.max-request-size 와 동일한 값으로 설정해도 좋습니다.
    max-swallow-size: 10MB

spring:
  servlet:
    multipart:
      # 파일 하나당 최대 크기를 10MB로 변경
      max-file-size: 10MB
      # 전체 요청의 최대 크기를 50MB로 변경 (여러 파일 업로드 고려)
      max-request-size: 50MB

  application:
    name: otvoo

  datasource:
    url: jdbc:postgresql://localhost:5432/otvoo_db
    username: otvoo_user
    password: otvoo_pass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: localhost
  elasticsearch:
    uris: http://3.38.186.207:9200

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  profiles:
    active:
      - dev

  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: never

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          maxCompletionTokens: 1000

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: otvoo1t@gmail.com
    password: ickfzkxkyyjtvukd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: info

weather:
  api:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    service-key: ${WEATHER_API_KEY}
  batch:
    base-time: "2300"

kakao:
  local:
    api:
      base-url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
      service-key: ${KAKAO_REST_API_KEY}

profile:
  default-image:
    url: https://your-s3-bucket.s3.region.amazonaws.com/default/profile.png
    filename: default-profile.png
    content-type: image/png
    size: 12345  # 바이트 단위
    width: 300
    height: 300

admin:
  name: 관리자
  email: abcde@email.com
  password: abcde123@

aws:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    presigned-expiration-seconds: ${S3_PRESIGNED_TTL}

  sqs:
    queue-name: otvoo_sqs_queue   # 실제 sqs queue 이름

sse:
  timeout: 1800000
  event-ttl-days: 7
  max-connections: 10000

stream:
  index-ttl-days: 7
  max-stream-length: 100000
  retention-days: 8
