spring:
  application:
    name: otvoo

  datasource:
    url: jdbc:postgresql://localhost:5432/otvoo_db
    username: otvoo_user
    password: otvoo_pass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: localhost

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  profiles:
    active:
      - dev

  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: never

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          maxCompletionTokens: 1000

  #임시
  batch:
    jdbc:
      initialize-schema: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: otvoo1t@gmail.com
    password: ickfzkxkyyjtvukd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: info

weather:
  api:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    service-key: ${WEATHER_API_KEY}
  batch:
    base-time: "2300"

kakao:
  local:
    api:
      base-url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
      service-key: ${KAKAO_REST_API_KEY}

profile:
  default-image:
    url: https://your-s3-bucket.s3.region.amazonaws.com/default/profile.png
    filename: default-profile.png
    content-type: image/png
    size: 12345  # 바이트 단위
    width: 300
    height: 300

admin:
  name: 관리자
  email: abcde@email.com
  password: abcde123@

aws:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    presigned-expiration-seconds: ${S3_PRESIGNED_TTL}

  sqs:
    queue-name: otvoo_sqs_queue   # 실제 sqs queue 이름

sse:
  timeout: 300_000
  event-ttl-seconds: 300
