spring:
  application:
    name: otvoo

  datasource:
    url: jdbc:postgresql://localhost:5432/otvoo_db
    username: otvoo_user
    password: otvoo_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  profiles:
    active:
      - dev
  sql:
    init:
      mode: never

  config:
    import: optional:file:.env[.properties]

data:
  redis:
    port: 6379
    host: localhost

logging:
  level:
    root: info

weather:
  api:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    service-key: ${WEATHER_API_KEY}

kakao:
  local:
    api:
      base-url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
      service-key: ${KAKAO_REST_API_KEY}

mail:
  host: smtp.gmail.com
  port: 587
  username: otvoo1t@gmail.com
  password: ickfzkxkyyjtvukd
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true