name: CD Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  # 0. PR 머지 확인 (dev → main merge)
  check-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR merged into main. Starting CD pipeline."

  # 1. 수동 승인 단계 (옵션)
  wait-for-approval:
    name: Wait for Approval
    runs-on: ubuntu-latest
    environment: production
    needs: check-merge
    steps:
      - run: echo "Deployment to production approved. Starting build and deploy process."

  # 2. 도커 이미지 빌드 및 ECR에 푸시
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: wait-for-approval
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

    steps:
      - uses: actions/checkout@v3

      - name: Extract Git Commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: chmod +x ./gradlew

      - name: Build Spring Boot Jar
        run: ./gradlew clean build --no-daemon   # clean 추가, test.yml과 일관성 맞춤

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: otvoo
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest 

  # 3. ECS에 배포
  deploy-backend:
    name: Deploy Backend to ECS
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1   # v1 (안정된 버전 사용)
        with:
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
          image: ${{ steps.login-ecr.outputs.registry }}/otvoo:${{ needs.build-and-push-image.outputs.sha_short }}
          container-name: ${{ secrets.ECS_CONTAINER_NAME }}

      - name: Deployment Complete
        run: echo "Backend deployment completed successfully!"
